name: flutter_starter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.0
  flutter_native_splash: ^2.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  intl: any
  google_fonts: ^5.1.0
  flutter_localizations:
    sdk: flutter
  logger: ^2.0.1
  get_it: ^7.6.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  injectable: ^2.2.0
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  skeletonizer: ^0.6.0
  loading_animation_widget: ^1.2.0+4
  infinite_scroll_pagination: ^4.0.0
  flutter_local_notifications: ^15.1.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  package_info_plus: ^4.1.0
  firebase_auth: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.3.0
  hive_generator: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300